### ISSUE TITLE
EXIF Orientation may already be applied by the canvas

### ISSUE THREAD

**Issue by byronigoe** [dfa1234/ngx-image-compress#64] opened 2021-11-14 18:57 UTC
CanvasRenderingContext2D.drawImage() automatically rotates the JPEG image based on the EXIF Orientation flag. Therefore applying the detected orientation a second time will rotate the image too much.

Perhaps it did not used to be the case, and perhaps it is not the case in some browsers, but at least it is in Chrome 95.0.4638.69

Here is an image I made for testing. The arrow points to the left in the raw data, but the EXIF Orientation value of 6 causes it to point up.
![up_exif](https://user-images.githubusercontent.com/10134042/141694544-496e4656-0b68-43f2-9e74-ba26626a559b.jpg)

**Comment by dfa1234** [comment] 2021-12-21 17:19
Not linked to issue but thank a lot @byronigoe for you contribution. Yesterday I merged your changes (on 2 MR I had to apply them manually because of conflict, since I also sent a lot of change myself, but it's there)

If Chrome is changing its internal canvas API it's a big issue, I will test it very soon

**Comment by dfa1234** [comment] 2022-01-31 22:00
I finally did a meaningful test and for what I see here, there is no problem.
As you can see in the screenshot, here the result image point on the right in Chrome Version 97.0.4692.99 (Official Build) (64-bit)

The first image is the raw data, the arrow is pointing up.

The second image is the result of the compression. 
It's pointing on the right as expected.
Why? If you run exiftool on your image, here what I get:
```bash
$ exiftool -Orientation up_exif.jpg
Orientation                     : Rotate 90 CW
```

So the arrow need to rotate 90 degree clockwise, and so is the result in the canvas.

Here the screenshot. I added your image to the list of demo-able image, if anyone need to be convinced: 

![Screenshot 2022-01-31 235313](https://user-images.githubusercontent.com/8502517/151879580-7462e45a-85fc-4763-b962-171df61f7428.png)

**Comment by byronigoe** [comment] 2022-02-01 02:31
@dfa1234 Your test shows the problem. The raw data has the arrow pointing left. Only after applying the EXIF orientation will the arrow point up (as you can see in the browser, which applies it). So, if you are getting the arrow pointing right, then you have rotated it again.

**Comment by dfa1234** [comment] 2022-02-01 07:12
@byronigoe  you are perfectly right
Here the file when I open it with GIMP
![image](https://user-images.githubusercontent.com/8502517/151926506-e4ad40da-6068-4516-a6f5-bb4314842776.png)

It's a real bummer.
All the complexity some year ago was that the browser was not taking in account the rotation when drawing on the canvas with CanvasRenderingContext2D.drawImage()
I need to dig a little more to understand what happened with this method implementation.
BTW the problem is the same with an up-to-date version or firefox (windows)

**Comment by dfa1234** [comment] 2022-02-01 07:22
#https://github.com/w3c/csswg-drafts/issues/4666

**Comment by dfa1234** [comment] 2022-02-01 07:24
Maybe it's possible to test the browser version or just disabled the code about the EXIF orentation.
We will check the options soons
More informations here : w3c/csswg-drafts#4666

**Comment by dfa1234** [comment] 2022-02-01 07:42
Tested on an real iphone 11 device

There is no problem 

![image](https://user-images.githubusercontent.com/8502517/151929991-629309f9-5268-4786-bae4-11a81936e7f2.png)

**Comment by dfa1234** [comment] 2022-02-01 07:50
Chrome 80 is ok. The new canvas API seems to be from Chrome 81+

![chrome 79](https://user-images.githubusercontent.com/8502517/151930917-5f4e0998-0b47-4a45-8b4b-2dfe573c4f5a.png)

**Closed** 2022-02-03 14:17 UTC
Labels: bug, willfix
